ci: jasypt support in postgres composite action

diff --git a/.github/actions/setup-postgres/action.yml b/.github/actions/setup-postgres/action.yml
--- a/.github/actions/setup-postgres/action.yml
+++ b/.github/actions/setup-postgres/action.yml
@@ -78,6 +78,15 @@ runs:
 
     - name: Initialize Database
       run: |
-        docker exec -i avenirs-postgres psql -U $POSTGRES_USER -d $POSTGRES_DB -f /tmp/init-db.sql
-        docker exec -i avenirs-postgres psql -U $POSTGRES_USER -d $POSTGRES_DB -f /tmp/init-test-db.sql
+        JASYPT_JAR=".github/lib/jasypt-1.9.3.jar"
+        [ -f "$JASYPT_JAR" ] || { echo -ne "\n\nError : JAR Jasypt not found in .github/lib\n\n"; exit 1; }
+
+        for FILE in /tmp/init-db.sql /tmp/init-test-db.sql; do \
+          encrypted=$(grep -o 'ENC([A-Za-z0-9+/=]*)' $FILE | sed -E 's/ENC\((.*)\)/\1/'); \
+          decrypted=$(java -cp "$JASYPT_JAR" org.jasypt.intf.cli.JasyptPBEStringDecryptionCLI input=$encrypted password=$JASYPT_ENCRYPTOR_PASSWORD algorithm=PBEWithMD5AndDES | grep -v '^$' | tail -n 1); \
+          sed -i "s|ENC($encrypted)|$decrypted|" $FILE; \
+        done \
+        && docker exec -i avenirs-postgres psql -U $POSTGRES_USER -d $POSTGRES_DB -f /tmp/init-db.sql \
+        && docker exec -i avenirs-postgres psql -U $POSTGRES_USER -d $POSTGRES_DB -f /tmp/init-test-db.sql \
+        && rm -f /tmp/init-db.sql /tmp/init-test-db.sql
       shell: bash
