fix: infite loop for app running test

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -56,12 +56,27 @@ jobs:
         env:
           SPRING_PROFILES_ACTIVE: test
 
-      - name: Wait for Application to Start
+      - name: Wait for Application to be Ready
         run: |
-          until curl --silent --fail http://localhost:8080/actuator/health; do
-            echo "Waiting for the application to start..."
-            sleep 5
-          done
+            echo "Waiting for Application to be ready..."
+            sleep 20
+            set +e
+            for i in {1..10}; do
+              STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:12000/actuator/health)
+              if [ "$STATUS" -eq 200 ]; then
+                echo "Application is ready."
+                break
+              fi
+              echo "Application is not ready yet... retrying in 10 seconds. Current status: $STATUS"
+              sleep 10
+            done
+            
+            # Vérification finale pour s'assurer que l'application est prête
+            if [ "$STATUS" -ne 200 ]; then
+              echo "Application failed to start after 10 attempts."
+              exit 1
+            fi
+      
 
       - name: Set up Python
         uses: actions/setup-python@v4
